'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''tdReservaUnidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdReservaUnidades As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''imgbtn_ReservaUnidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtn_ReservaUnidades As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tdApoyoFabricante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdApoyoFabricante As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''imgbtn_ApoyoFabricante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtn_ApoyoFabricante As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tdBonos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBonos As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''imgbtn_Bonos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtn_Bonos As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tdAdministracion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdAdministracion As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''imgbtn_Administracion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtn_Administracion As Global.System.Web.UI.WebControls.ImageButton
End Class
