'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1026
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1026.
'
Namespace WS_RDA_DES
    
    'CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_CONSULTA_RDA", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_CONSULTA_RDA
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZrfcConsultaRdaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SGCVU.WS.My.MySettings.Default.SGCVU_WS_WS_RDA_DES_ZWS_CONSULTA_RDA
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZrfcConsultaRdaCompleted As ZrfcConsultaRdaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZrfcConsultaRda(<System.Xml.Serialization.XmlElementAttribute("ZrfcConsultaRda", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZrfcConsultaRda1 As ZrfcConsultaRda) As <System.Xml.Serialization.XmlElementAttribute("ZrfcConsultaRdaResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZrfcConsultaRdaResponse
            Dim results() As Object = Me.Invoke("ZrfcConsultaRda", New Object() {ZrfcConsultaRda1})
            Return CType(results(0),ZrfcConsultaRdaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZrfcConsultaRdaAsync(ByVal ZrfcConsultaRda1 As ZrfcConsultaRda)
            Me.ZrfcConsultaRdaAsync(ZrfcConsultaRda1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZrfcConsultaRdaAsync(ByVal ZrfcConsultaRda1 As ZrfcConsultaRda, ByVal userState As Object)
            If (Me.ZrfcConsultaRdaOperationCompleted Is Nothing) Then
                Me.ZrfcConsultaRdaOperationCompleted = AddressOf Me.OnZrfcConsultaRdaOperationCompleted
            End If
            Me.InvokeAsync("ZrfcConsultaRda", New Object() {ZrfcConsultaRda1}, Me.ZrfcConsultaRdaOperationCompleted, userState)
        End Sub
        
        Private Sub OnZrfcConsultaRdaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZrfcConsultaRdaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZrfcConsultaRdaCompleted(Me, New ZrfcConsultaRdaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZrfcConsultaRda
        
        Private fechacreacionfField As String
        
        Private fechacreacioniField As String
        
        Private fechamodfField As String
        
        Private fechamodiField As String
        
        Private horacreacionfField As String
        
        Private horacreacioniField As String
        
        Private horamodfField As String
        
        Private horamodiField As String
        
        Private tGuidField() As ZesGuidRda
        
        Private tIdoperacionField() As ZesIdoperacion
        
        Private tOrdenasignadaField() As ZesOrdasignada
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fechacreacionf() As String
            Get
                Return Me.fechacreacionfField
            End Get
            Set
                Me.fechacreacionfField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fechacreacioni() As String
            Get
                Return Me.fechacreacioniField
            End Get
            Set
                Me.fechacreacioniField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fechamodf() As String
            Get
                Return Me.fechamodfField
            End Get
            Set
                Me.fechamodfField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fechamodi() As String
            Get
                Return Me.fechamodiField
            End Get
            Set
                Me.fechamodiField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Horacreacionf() As String
            Get
                Return Me.horacreacionfField
            End Get
            Set
                Me.horacreacionfField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Horacreacioni() As String
            Get
                Return Me.horacreacioniField
            End Get
            Set
                Me.horacreacioniField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Horamodf() As String
            Get
                Return Me.horamodfField
            End Get
            Set
                Me.horamodfField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Horamodi() As String
            Get
                Return Me.horamodiField
            End Get
            Set
                Me.horamodiField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TGuid() As ZesGuidRda()
            Get
                Return Me.tGuidField
            End Get
            Set
                Me.tGuidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TIdoperacion() As ZesIdoperacion()
            Get
                Return Me.tIdoperacionField
            End Get
            Set
                Me.tIdoperacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TOrdenasignada() As ZesOrdasignada()
            Get
                Return Me.tOrdenasignadaField
            End Get
            Set
                Me.tOrdenasignadaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesGuidRda
        
        Private guidField() As Byte
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesTabaccesorios
        
        Private mandtField As String
        
        Private guidField() As Byte
        
        Private guidposField() As Byte
        
        Private idposicionField As String
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private nvadescripcionField As String
        
        Private cantidadField As Decimal
        
        Private unidmedidaField As String
        
        Private vlistaunitariaField As Decimal
        
        Private vtotalField As Decimal
        
        Private monedaField As String
        
        Private checketField As String
        
        Private nroparteField As String
        
        Private idpedidoField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guidpos() As Byte()
            Get
                Return Me.guidposField
            End Get
            Set
                Me.guidposField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idposicion() As String
            Get
                Return Me.idposicionField
            End Get
            Set
                Me.idposicionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nvadescripcion() As String
            Get
                Return Me.nvadescripcionField
            End Get
            Set
                Me.nvadescripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unidmedida() As String
            Get
                Return Me.unidmedidaField
            End Get
            Set
                Me.unidmedidaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vlistaunitaria() As Decimal
            Get
                Return Me.vlistaunitariaField
            End Get
            Set
                Me.vlistaunitariaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vtotal() As Decimal
            Get
                Return Me.vtotalField
            End Get
            Set
                Me.vtotalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Checket() As String
            Get
                Return Me.checketField
            End Get
            Set
                Me.checketField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nroparte() As String
            Get
                Return Me.nroparteField
            End Get
            Set
                Me.nroparteField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idpedido() As String
            Get
                Return Me.idpedidoField
            End Get
            Set
                Me.idpedidoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesRecompra
        
        Private mandtField As String
        
        Private guidField() As Byte
        
        Private guidposField() As Byte
        
        Private idposicionField As String
        
        Private secuenciaField As String
        
        Private horasField As String
        
        Private aniosField As String
        
        Private montoField As Decimal
        
        Private monedaField As String
        
        Private idpedidoField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guidpos() As Byte()
            Get
                Return Me.guidposField
            End Get
            Set
                Me.guidposField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idposicion() As String
            Get
                Return Me.idposicionField
            End Get
            Set
                Me.idposicionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Secuencia() As String
            Get
                Return Me.secuenciaField
            End Get
            Set
                Me.secuenciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Horas() As String
            Get
                Return Me.horasField
            End Get
            Set
                Me.horasField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Anios() As String
            Get
                Return Me.aniosField
            End Get
            Set
                Me.aniosField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Monto() As Decimal
            Get
                Return Me.montoField
            End Get
            Set
                Me.montoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idpedido() As String
            Get
                Return Me.idpedidoField
            End Get
            Set
                Me.idpedidoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesRda
        
        Private mandtField As String
        
        Private guidField() As Byte
        
        Private idpedidoField As String
        
        Private claseField As String
        
        Private clasetxtField As String
        
        Private occlienteField As String
        
        Private mercadoField As String
        
        Private mercadoTxtField As String
        
        Private statusField As String
        
        Private statusTxtField As String
        
      Private fechaField As String
        
      Private fechaEstFactField As String
        
        Private orgfactField As String
        
        Private orgfactTxtField As String
        
        Private ofiventasfacField As String
        
        Private ofiventasfacTxtField As String
        
        Private oportunidadField As String
        
        Private paisField As String
        
        Private paisTxtField As String
        
        Private departamentoField As String
        
        Private depTxtField As String
        
        Private provinciaField As String
        
        Private provTxtField As String
        
        Private trabPrincField As String
        
        Private trabPrincTxtField As String
        
        Private tipoAplicField As String
        
        Private tipoAplicTxtField As String
        
        Private lugOperField As String
        
        Private instlcnsField As String
        
        Private instlcnsTxField As String
        
        Private grupFeField As String
        
        Private grupFeTxtField As String
        
        Private lugarEntField As String
        
        Private lugarEntTxtField As String
        
        Private entregaClntField As String
        
        Private entregaClntTxtField As String
        
        Private otradirField As String
        
        Private otroLugEntField As String
        
        Private otroField As String
        
      Private fechaEntregaField As String
        
      Private fechaArmadoField As String
        
        Private condEntregaField As String
        
        Private condEntregaTxtField As String
        
        Private nroMotorField As String
        
        Private mrgnInicialField As Decimal
        
        Private mrgnComercialField As Decimal
        
        Private apoyoFabField As String
        
        Private apoyoFabTxtField As String
        
        Private tipoApoyoField As String
        
        Private tipoApoyoTxtField As String
        
        Private staFinanzeField As String
        
        Private staWorktoolsField As String
        
        Private staEppField As String
        
        Private staCsaField As String
        
        Private staPartsField As String
        
        Private staPriceField As String
        
        Private staRentalField As String
        
        Private otroApFabField As String
        
        Private montoApoyoField As Decimal
        
        Private monedaField As String
        
        Private incoterms1Field As String
        
        Private incoterms2Field As String
        
        Private trabAlturaField As String
        
        Private alturaField As String
        
        Private orgVentasField As String
        
        Private orgVentasTxtField As String
        
        Private canalDistField As String
        
        Private canalDistTxtField As String
        
        Private ofiVentasField As String
        
        Private ofiVentasTxtField As String
        
        Private sectorField As String
        
        Private sectorTxtField As String
        
        Private unidadOrgField As String
        
        Private unidadOrgTxtField As String
        
        Private grupoVendorField As String
        
        Private grupoVendorTxtField As String
        
        Private eliminadoField As String
        
      Private fechacreField As String
        
      Private horacreField As String
        
      Private fechamodField As String
        
      Private horamodField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idpedido() As String
            Get
                Return Me.idpedidoField
            End Get
            Set
                Me.idpedidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Clase() As String
            Get
                Return Me.claseField
            End Get
            Set
                Me.claseField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Clasetxt() As String
            Get
                Return Me.clasetxtField
            End Get
            Set
                Me.clasetxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Occliente() As String
            Get
                Return Me.occlienteField
            End Get
            Set
                Me.occlienteField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mercado() As String
            Get
                Return Me.mercadoField
            End Get
            Set
                Me.mercadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MercadoTxt() As String
            Get
                Return Me.mercadoTxtField
            End Get
            Set
                Me.mercadoTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StatusTxt() As String
            Get
                Return Me.statusTxtField
            End Get
            Set
                Me.statusTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property Fecha() As String
         Get
            Return Me.fechaField
         End Get
         Set(ByVal value As String)
            Me.fechaField = value
         End Set
      End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property FechaEstFact() As String
         Get
            Return Me.fechaEstFactField
         End Get
         Set(ByVal value As String)
            Me.fechaEstFactField = value
         End Set
      End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Orgfact() As String
            Get
                Return Me.orgfactField
            End Get
            Set
                Me.orgfactField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OrgfactTxt() As String
            Get
                Return Me.orgfactTxtField
            End Get
            Set
                Me.orgfactTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ofiventasfac() As String
            Get
                Return Me.ofiventasfacField
            End Get
            Set
                Me.ofiventasfacField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OfiventasfacTxt() As String
            Get
                Return Me.ofiventasfacTxtField
            End Get
            Set
                Me.ofiventasfacTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Oportunidad() As String
            Get
                Return Me.oportunidadField
            End Get
            Set
                Me.oportunidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Pais() As String
            Get
                Return Me.paisField
            End Get
            Set
                Me.paisField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PaisTxt() As String
            Get
                Return Me.paisTxtField
            End Get
            Set
                Me.paisTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Departamento() As String
            Get
                Return Me.departamentoField
            End Get
            Set
                Me.departamentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DepTxt() As String
            Get
                Return Me.depTxtField
            End Get
            Set
                Me.depTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Provincia() As String
            Get
                Return Me.provinciaField
            End Get
            Set
                Me.provinciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ProvTxt() As String
            Get
                Return Me.provTxtField
            End Get
            Set
                Me.provTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TrabPrinc() As String
            Get
                Return Me.trabPrincField
            End Get
            Set
                Me.trabPrincField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TrabPrincTxt() As String
            Get
                Return Me.trabPrincTxtField
            End Get
            Set
                Me.trabPrincTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TipoAplic() As String
            Get
                Return Me.tipoAplicField
            End Get
            Set
                Me.tipoAplicField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TipoAplicTxt() As String
            Get
                Return Me.tipoAplicTxtField
            End Get
            Set
                Me.tipoAplicTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LugOper() As String
            Get
                Return Me.lugOperField
            End Get
            Set
                Me.lugOperField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Instlcns() As String
            Get
                Return Me.instlcnsField
            End Get
            Set
                Me.instlcnsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property InstlcnsTx() As String
            Get
                Return Me.instlcnsTxField
            End Get
            Set
                Me.instlcnsTxField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GrupFe() As String
            Get
                Return Me.grupFeField
            End Get
            Set
                Me.grupFeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GrupFeTxt() As String
            Get
                Return Me.grupFeTxtField
            End Get
            Set
                Me.grupFeTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LugarEnt() As String
            Get
                Return Me.lugarEntField
            End Get
            Set
                Me.lugarEntField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LugarEntTxt() As String
            Get
                Return Me.lugarEntTxtField
            End Get
            Set
                Me.lugarEntTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EntregaClnt() As String
            Get
                Return Me.entregaClntField
            End Get
            Set
                Me.entregaClntField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EntregaClntTxt() As String
            Get
                Return Me.entregaClntTxtField
            End Get
            Set
                Me.entregaClntTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Otradir() As String
            Get
                Return Me.otradirField
            End Get
            Set
                Me.otradirField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OtroLugEnt() As String
            Get
                Return Me.otroLugEntField
            End Get
            Set
                Me.otroLugEntField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Otro() As String
            Get
                Return Me.otroField
            End Get
            Set
                Me.otroField = value
            End Set
        End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property FechaEntrega() As String
         Get
            Return Me.fechaEntregaField
         End Get
         Set(ByVal value As String)
            Me.fechaEntregaField = value
         End Set
      End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property FechaArmado() As String
         Get
            Return Me.fechaArmadoField
         End Get
         Set(ByVal value As String)
            Me.fechaArmadoField = value
         End Set
      End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CondEntrega() As String
            Get
                Return Me.condEntregaField
            End Get
            Set
                Me.condEntregaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CondEntregaTxt() As String
            Get
                Return Me.condEntregaTxtField
            End Get
            Set
                Me.condEntregaTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NroMotor() As String
            Get
                Return Me.nroMotorField
            End Get
            Set
                Me.nroMotorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MrgnInicial() As Decimal
            Get
                Return Me.mrgnInicialField
            End Get
            Set
                Me.mrgnInicialField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MrgnComercial() As Decimal
            Get
                Return Me.mrgnComercialField
            End Get
            Set
                Me.mrgnComercialField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ApoyoFab() As String
            Get
                Return Me.apoyoFabField
            End Get
            Set
                Me.apoyoFabField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ApoyoFabTxt() As String
            Get
                Return Me.apoyoFabTxtField
            End Get
            Set
                Me.apoyoFabTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TipoApoyo() As String
            Get
                Return Me.tipoApoyoField
            End Get
            Set
                Me.tipoApoyoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TipoApoyoTxt() As String
            Get
                Return Me.tipoApoyoTxtField
            End Get
            Set
                Me.tipoApoyoTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StaFinanze() As String
            Get
                Return Me.staFinanzeField
            End Get
            Set
                Me.staFinanzeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StaWorktools() As String
            Get
                Return Me.staWorktoolsField
            End Get
            Set
                Me.staWorktoolsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StaEpp() As String
            Get
                Return Me.staEppField
            End Get
            Set
                Me.staEppField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StaCsa() As String
            Get
                Return Me.staCsaField
            End Get
            Set
                Me.staCsaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StaParts() As String
            Get
                Return Me.staPartsField
            End Get
            Set
                Me.staPartsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StaPrice() As String
            Get
                Return Me.staPriceField
            End Get
            Set
                Me.staPriceField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StaRental() As String
            Get
                Return Me.staRentalField
            End Get
            Set
                Me.staRentalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OtroApFab() As String
            Get
                Return Me.otroApFabField
            End Get
            Set
                Me.otroApFabField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MontoApoyo() As Decimal
            Get
                Return Me.montoApoyoField
            End Get
            Set
                Me.montoApoyoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Incoterms1() As String
            Get
                Return Me.incoterms1Field
            End Get
            Set
                Me.incoterms1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Incoterms2() As String
            Get
                Return Me.incoterms2Field
            End Get
            Set
                Me.incoterms2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TrabAltura() As String
            Get
                Return Me.trabAlturaField
            End Get
            Set
                Me.trabAlturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Altura() As String
            Get
                Return Me.alturaField
            End Get
            Set
                Me.alturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OrgVentas() As String
            Get
                Return Me.orgVentasField
            End Get
            Set
                Me.orgVentasField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OrgVentasTxt() As String
            Get
                Return Me.orgVentasTxtField
            End Get
            Set
                Me.orgVentasTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CanalDist() As String
            Get
                Return Me.canalDistField
            End Get
            Set
                Me.canalDistField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CanalDistTxt() As String
            Get
                Return Me.canalDistTxtField
            End Get
            Set
                Me.canalDistTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OfiVentas() As String
            Get
                Return Me.ofiVentasField
            End Get
            Set
                Me.ofiVentasField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OfiVentasTxt() As String
            Get
                Return Me.ofiVentasTxtField
            End Get
            Set
                Me.ofiVentasTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sector() As String
            Get
                Return Me.sectorField
            End Get
            Set
                Me.sectorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SectorTxt() As String
            Get
                Return Me.sectorTxtField
            End Get
            Set
                Me.sectorTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnidadOrg() As String
            Get
                Return Me.unidadOrgField
            End Get
            Set
                Me.unidadOrgField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnidadOrgTxt() As String
            Get
                Return Me.unidadOrgTxtField
            End Get
            Set
                Me.unidadOrgTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GrupoVendor() As String
            Get
                Return Me.grupoVendorField
            End Get
            Set
                Me.grupoVendorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GrupoVendorTxt() As String
            Get
                Return Me.grupoVendorTxtField
            End Get
            Set
                Me.grupoVendorTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Eliminado() As String
            Get
                Return Me.eliminadoField
            End Get
            Set
                Me.eliminadoField = value
            End Set
        End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property Fechacre() As String
         Get
            Return Me.fechacreField
         End Get
         Set(ByVal value As String)
            Me.fechacreField = value
         End Set
      End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property Horacre() As String
         Get
            Return Me.horacreField
         End Get
         Set(ByVal value As String)
            Me.horacreField = value
         End Set
      End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property Fechamod() As String
         Get
            Return Me.fechamodField
         End Get
         Set(ByVal value As String)
            Me.fechamodField = value
         End Set
      End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property Horamod() As String
         Get
            Return Me.horamodField
         End Get
         Set(ByVal value As String)
            Me.horamodField = value
         End Set
      End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesPosicion
        
        Private mandtField As String
        
        Private guidField() As Byte
        
        Private guidposField() As Byte
        
        Private idposicionField As String
        
        Private idpedidoField As String
        
        Private idproductoField As String
        
        Private denominacionField As String
        
        Private descripcion2Field As String
        
        Private cantidadField As Decimal
        
        Private umedidaField As String
        
        Private umedidatxtField As String
        
        Private clcField As String
        
        Private statusField As String
        
        Private statusTxtField As String
        
        Private tipoPosField As String
        
        Private tipoPosTxtField As String
        
        Private catProductoField As String
        
        Private formaPagoField As String
        
        Private formaPagoTxtField As String
        
        Private diasCreditoField As Byte
        
        Private plazoEntregaField As String
        
        Private promUsoField As Byte
        
        Private interloteField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guidpos() As Byte()
            Get
                Return Me.guidposField
            End Get
            Set
                Me.guidposField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idposicion() As String
            Get
                Return Me.idposicionField
            End Get
            Set
                Me.idposicionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idpedido() As String
            Get
                Return Me.idpedidoField
            End Get
            Set
                Me.idpedidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idproducto() As String
            Get
                Return Me.idproductoField
            End Get
            Set
                Me.idproductoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Denominacion() As String
            Get
                Return Me.denominacionField
            End Get
            Set
                Me.denominacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Descripcion2() As String
            Get
                Return Me.descripcion2Field
            End Get
            Set
                Me.descripcion2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Umedida() As String
            Get
                Return Me.umedidaField
            End Get
            Set
                Me.umedidaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Umedidatxt() As String
            Get
                Return Me.umedidatxtField
            End Get
            Set
                Me.umedidatxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Clc() As String
            Get
                Return Me.clcField
            End Get
            Set
                Me.clcField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StatusTxt() As String
            Get
                Return Me.statusTxtField
            End Get
            Set
                Me.statusTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TipoPos() As String
            Get
                Return Me.tipoPosField
            End Get
            Set
                Me.tipoPosField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TipoPosTxt() As String
            Get
                Return Me.tipoPosTxtField
            End Get
            Set
                Me.tipoPosTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CatProducto() As String
            Get
                Return Me.catProductoField
            End Get
            Set
                Me.catProductoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FormaPago() As String
            Get
                Return Me.formaPagoField
            End Get
            Set
                Me.formaPagoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FormaPagoTxt() As String
            Get
                Return Me.formaPagoTxtField
            End Get
            Set
                Me.formaPagoTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DiasCredito() As Byte
            Get
                Return Me.diasCreditoField
            End Get
            Set
                Me.diasCreditoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PlazoEntrega() As String
            Get
                Return Me.plazoEntregaField
            End Get
            Set
                Me.plazoEntregaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PromUso() As Byte
            Get
                Return Me.promUsoField
            End Get
            Set
                Me.promUsoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Interlote() As String
            Get
                Return Me.interloteField
            End Get
            Set
                Me.interloteField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesListaImplicado
        
        Private mandtField As String
        
        Private guidField() As Byte
        
        Private idsapsocnegField As String
        
        Private funcionField As String
        
        Private funciontxtField As String
        
        Private nombreField As String
        
        Private idextsocnegField As String
        
        Private idpedidoField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idsapsocneg() As String
            Get
                Return Me.idsapsocnegField
            End Get
            Set
                Me.idsapsocnegField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Funcion() As String
            Get
                Return Me.funcionField
            End Get
            Set
                Me.funcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Funciontxt() As String
            Get
                Return Me.funciontxtField
            End Get
            Set
                Me.funciontxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idextsocneg() As String
            Get
                Return Me.idextsocnegField
            End Get
            Set
                Me.idextsocnegField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idpedido() As String
            Get
                Return Me.idpedidoField
            End Get
            Set
                Me.idpedidoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesDetPrecios
        
        Private mandtField As String
        
        Private guidField() As Byte
        
        Private guidposField() As Byte
        
        Private idposicionField As String
        
        Private elementoField As String
        
        Private elementoTxtField As String
        
        Private valorField As Decimal
        
        Private monedaField As String
        
        Private idpedidoField As String
        
        Private estatusField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guidpos() As Byte()
            Get
                Return Me.guidposField
            End Get
            Set
                Me.guidposField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idposicion() As String
            Get
                Return Me.idposicionField
            End Get
            Set
                Me.idposicionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Elemento() As String
            Get
                Return Me.elementoField
            End Get
            Set
                Me.elementoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ElementoTxt() As String
            Get
                Return Me.elementoTxtField
            End Get
            Set
                Me.elementoTxtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idpedido() As String
            Get
                Return Me.idpedidoField
            End Get
            Set
                Me.idpedidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Estatus() As String
            Get
                Return Me.estatusField
            End Get
            Set
                Me.estatusField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesBeneficios
        
        Private mandtField As String
        
        Private guidField() As Byte
        
        Private guidposField() As Byte
        
        Private idposicionField As String
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private cantidadField As Decimal
        
        Private unidmedidaField As String
        
        Private checketField As String
        
        Private idpedidoField As String
        
        Private costoField As Decimal
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guidpos() As Byte()
            Get
                Return Me.guidposField
            End Get
            Set
                Me.guidposField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idposicion() As String
            Get
                Return Me.idposicionField
            End Get
            Set
                Me.idposicionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unidmedida() As String
            Get
                Return Me.unidmedidaField
            End Get
            Set
                Me.unidmedidaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Checket() As String
            Get
                Return Me.checketField
            End Get
            Set
                Me.checketField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idpedido() As String
            Get
                Return Me.idpedidoField
            End Get
            Set
                Me.idpedidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Costo() As Decimal
            Get
                Return Me.costoField
            End Get
            Set
                Me.costoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesAsigEquipo
        
        Private mandtField As String
        
        Private guidField() As Byte
        
        Private numeroField As String
        
        Private idpedidoField As String
        
        Private ordasignadaField As String
        
        Private serieField As String
        
        Private ctainventarioField As String
        
        Private coddbsField As String
        
        Private afabricacionField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property Guid() As Byte()
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idpedido() As String
            Get
                Return Me.idpedidoField
            End Get
            Set
                Me.idpedidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ordasignada() As String
            Get
                Return Me.ordasignadaField
            End Get
            Set
                Me.ordasignadaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ctainventario() As String
            Get
                Return Me.ctainventarioField
            End Get
            Set
                Me.ctainventarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Coddbs() As String
            Get
                Return Me.coddbsField
            End Get
            Set
                Me.coddbsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Afabricacion() As String
            Get
                Return Me.afabricacionField
            End Get
            Set
                Me.afabricacionField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesOrdasignada
        
        Private ordasignadaField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ordasignada() As String
            Get
                Return Me.ordasignadaField
            End Get
            Set
                Me.ordasignadaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZesIdoperacion
        
        Private idoperacionField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idoperacion() As String
            Get
                Return Me.idoperacionField
            End Get
            Set
                Me.idoperacionField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZrfcConsultaRdaResponse
        
        Private etZasigEquipoField() As ZesAsigEquipo
        
        Private etZbeneficiosField() As ZesBeneficios
        
        Private etZdetPreciosField() As ZesDetPrecios
        
        Private etZlistaImplicadoField() As ZesListaImplicado
        
        Private etZposicionField() As ZesPosicion
        
        Private etZrdaField() As ZesRda
        
        Private etZrecompraField() As ZesRecompra
        
        Private etZtabaccesoriosField() As ZesTabaccesorios
        
        Private resultField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EtZasigEquipo() As ZesAsigEquipo()
            Get
                Return Me.etZasigEquipoField
            End Get
            Set
                Me.etZasigEquipoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EtZbeneficios() As ZesBeneficios()
            Get
                Return Me.etZbeneficiosField
            End Get
            Set
                Me.etZbeneficiosField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EtZdetPrecios() As ZesDetPrecios()
            Get
                Return Me.etZdetPreciosField
            End Get
            Set
                Me.etZdetPreciosField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EtZlistaImplicado() As ZesListaImplicado()
            Get
                Return Me.etZlistaImplicadoField
            End Get
            Set
                Me.etZlistaImplicadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EtZposicion() As ZesPosicion()
            Get
                Return Me.etZposicionField
            End Get
            Set
                Me.etZposicionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EtZrda() As ZesRda()
            Get
                Return Me.etZrdaField
            End Get
            Set
                Me.etZrdaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EtZrecompra() As ZesRecompra()
            Get
                Return Me.etZrecompraField
            End Get
            Set
                Me.etZrecompraField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EtZtabaccesorios() As ZesTabaccesorios()
            Get
                Return Me.etZtabaccesoriosField
            End Get
            Set
                Me.etZtabaccesoriosField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Result() As String
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ZrfcConsultaRdaCompletedEventHandler(ByVal sender As Object, ByVal e As ZrfcConsultaRdaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZrfcConsultaRdaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZrfcConsultaRdaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZrfcConsultaRdaResponse)
            End Get
        End Property
    End Class
End Namespace
