'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1026
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://fsacrmdevqa.dominio.ferreyros.com.pe:8002/sap/bc/srt/rfc/sap/zws_gestion_c"& _ 
            "omercial/200/zws_gestion_comercial/binding")>  _
        Public ReadOnly Property SGCVU_WS_WS_CRM_QA_ZWS_GESTION_COMERCIAL() As String
            Get
                Return CType(Me("SGCVU_WS_WS_CRM_QA_ZWS_GESTION_COMERCIAL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://fsacrmdevqa.dominio.ferreyros.com.pe:8002/sap/bc/srt/rfc/sap/zws_consulta_"& _ 
            "rda/200/zws_consulta_rda/zws_consulta_rda")>  _
        Public ReadOnly Property SGCVU_WS_WS_RDA_QA_ZWS_CONSULTA_RDA() As String
            Get
                Return CType(Me("SGCVU_WS_WS_RDA_QA_ZWS_CONSULTA_RDA"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://fsacrmdevqa.dominio.ferreyros.com.pe:8001/sap/bc/srt/rfc/sap/zws_consulta_"& _ 
            "rda/100/zws_consulta_rda/zws_consulta_rda")>  _
        Public ReadOnly Property SGCVU_WS_WS_RDA_DES_ZWS_CONSULTA_RDA() As String
            Get
                Return CType(Me("SGCVU_WS_WS_RDA_DES_ZWS_CONSULTA_RDA"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://fsacrmdevqa.dominio.ferreyros.com.pe:8001/sap/bc/srt/rfc/sap/zws_gestion_c"& _ 
            "omercial/100/zws_gestion_comercial/binding")>  _
        Public ReadOnly Property SGCVU_WS_WS_CRM_DES_ZWS_GESTION_COMERCIAL() As String
            Get
                Return CType(Me("SGCVU_WS_WS_CRM_DES_ZWS_GESTION_COMERCIAL"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SGCVU.WS.My.MySettings
            Get
                Return Global.SGCVU.WS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
