'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1026
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1026.
'
Namespace WS_CRM_DES
    
    'CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="binding", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZWS_GESTION_COMERCIAL
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZSOA_DATA_SOCIO_NEGOCIOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ZSOA_DATA_PRODUCTSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ZSOA_DATA_EMPLEADOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ZSOA_DATA_OPORTUNIDADOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SGCVU.WS.My.MySettings.Default.SGCVU_WS_WS_CRM_DES_ZWS_GESTION_COMERCIAL
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZSOA_DATA_SOCIO_NEGOCIOCompleted As ZSOA_DATA_SOCIO_NEGOCIOCompletedEventHandler
        
        '''<remarks/>
        Public Event ZSOA_DATA_PRODUCTSCompleted As ZSOA_DATA_PRODUCTSCompletedEventHandler
        
        '''<remarks/>
        Public Event ZSOA_DATA_EMPLEADOCompleted As ZSOA_DATA_EMPLEADOCompletedEventHandler
        
        '''<remarks/>
        Public Event ZSOA_DATA_OPORTUNIDADCompleted As ZSOA_DATA_OPORTUNIDADCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZSOA_DATA_SOCIO_NEGOCIO(<System.Xml.Serialization.XmlElementAttribute("ZSOA_DATA_SOCIO_NEGOCIO", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal ZSOA_DATA_SOCIO_NEGOCIO1 As ZSOA_DATA_SOCIO_NEGOCIO) As <System.Xml.Serialization.XmlElementAttribute("ZSOA_DATA_SOCIO_NEGOCIOResponse", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ZSOA_DATA_SOCIO_NEGOCIOResponse
            Dim results() As Object = Me.Invoke("ZSOA_DATA_SOCIO_NEGOCIO", New Object() {ZSOA_DATA_SOCIO_NEGOCIO1})
            Return CType(results(0),ZSOA_DATA_SOCIO_NEGOCIOResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZSOA_DATA_SOCIO_NEGOCIOAsync(ByVal ZSOA_DATA_SOCIO_NEGOCIO1 As ZSOA_DATA_SOCIO_NEGOCIO)
            Me.ZSOA_DATA_SOCIO_NEGOCIOAsync(ZSOA_DATA_SOCIO_NEGOCIO1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZSOA_DATA_SOCIO_NEGOCIOAsync(ByVal ZSOA_DATA_SOCIO_NEGOCIO1 As ZSOA_DATA_SOCIO_NEGOCIO, ByVal userState As Object)
            If (Me.ZSOA_DATA_SOCIO_NEGOCIOOperationCompleted Is Nothing) Then
                Me.ZSOA_DATA_SOCIO_NEGOCIOOperationCompleted = AddressOf Me.OnZSOA_DATA_SOCIO_NEGOCIOOperationCompleted
            End If
            Me.InvokeAsync("ZSOA_DATA_SOCIO_NEGOCIO", New Object() {ZSOA_DATA_SOCIO_NEGOCIO1}, Me.ZSOA_DATA_SOCIO_NEGOCIOOperationCompleted, userState)
        End Sub
        
        Private Sub OnZSOA_DATA_SOCIO_NEGOCIOOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZSOA_DATA_SOCIO_NEGOCIOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZSOA_DATA_SOCIO_NEGOCIOCompleted(Me, New ZSOA_DATA_SOCIO_NEGOCIOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZSOA_DATA_PRODUCTS(<System.Xml.Serialization.XmlElementAttribute("ZSOA_DATA_PRODUCTS", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal ZSOA_DATA_PRODUCTS1 As ZSOA_DATA_PRODUCTS) As <System.Xml.Serialization.XmlElementAttribute("ZSOA_DATA_PRODUCTSResponse", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ZSOA_DATA_PRODUCTSResponse
            Dim results() As Object = Me.Invoke("ZSOA_DATA_PRODUCTS", New Object() {ZSOA_DATA_PRODUCTS1})
            Return CType(results(0),ZSOA_DATA_PRODUCTSResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZSOA_DATA_PRODUCTSAsync(ByVal ZSOA_DATA_PRODUCTS1 As ZSOA_DATA_PRODUCTS)
            Me.ZSOA_DATA_PRODUCTSAsync(ZSOA_DATA_PRODUCTS1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZSOA_DATA_PRODUCTSAsync(ByVal ZSOA_DATA_PRODUCTS1 As ZSOA_DATA_PRODUCTS, ByVal userState As Object)
            If (Me.ZSOA_DATA_PRODUCTSOperationCompleted Is Nothing) Then
                Me.ZSOA_DATA_PRODUCTSOperationCompleted = AddressOf Me.OnZSOA_DATA_PRODUCTSOperationCompleted
            End If
            Me.InvokeAsync("ZSOA_DATA_PRODUCTS", New Object() {ZSOA_DATA_PRODUCTS1}, Me.ZSOA_DATA_PRODUCTSOperationCompleted, userState)
        End Sub
        
        Private Sub OnZSOA_DATA_PRODUCTSOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZSOA_DATA_PRODUCTSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZSOA_DATA_PRODUCTSCompleted(Me, New ZSOA_DATA_PRODUCTSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZSOA_DATA_EMPLEADO(<System.Xml.Serialization.XmlElementAttribute("ZSOA_DATA_EMPLEADO", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal ZSOA_DATA_EMPLEADO1 As ZSOA_DATA_EMPLEADO) As <System.Xml.Serialization.XmlElementAttribute("ZSOA_DATA_EMPLEADOResponse", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ZSOA_DATA_EMPLEADOResponse
            Dim results() As Object = Me.Invoke("ZSOA_DATA_EMPLEADO", New Object() {ZSOA_DATA_EMPLEADO1})
            Return CType(results(0),ZSOA_DATA_EMPLEADOResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZSOA_DATA_EMPLEADOAsync(ByVal ZSOA_DATA_EMPLEADO1 As ZSOA_DATA_EMPLEADO)
            Me.ZSOA_DATA_EMPLEADOAsync(ZSOA_DATA_EMPLEADO1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZSOA_DATA_EMPLEADOAsync(ByVal ZSOA_DATA_EMPLEADO1 As ZSOA_DATA_EMPLEADO, ByVal userState As Object)
            If (Me.ZSOA_DATA_EMPLEADOOperationCompleted Is Nothing) Then
                Me.ZSOA_DATA_EMPLEADOOperationCompleted = AddressOf Me.OnZSOA_DATA_EMPLEADOOperationCompleted
            End If
            Me.InvokeAsync("ZSOA_DATA_EMPLEADO", New Object() {ZSOA_DATA_EMPLEADO1}, Me.ZSOA_DATA_EMPLEADOOperationCompleted, userState)
        End Sub
        
        Private Sub OnZSOA_DATA_EMPLEADOOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZSOA_DATA_EMPLEADOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZSOA_DATA_EMPLEADOCompleted(Me, New ZSOA_DATA_EMPLEADOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZSOA_DATA_OPORTUNIDAD(<System.Xml.Serialization.XmlElementAttribute("ZSOA_DATA_OPORTUNIDAD", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal ZSOA_DATA_OPORTUNIDAD1 As ZSOA_DATA_OPORTUNIDAD) As <System.Xml.Serialization.XmlElementAttribute("ZSOA_DATA_OPORTUNIDADResponse", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ZSOA_DATA_OPORTUNIDADResponse
            Dim results() As Object = Me.Invoke("ZSOA_DATA_OPORTUNIDAD", New Object() {ZSOA_DATA_OPORTUNIDAD1})
            Return CType(results(0),ZSOA_DATA_OPORTUNIDADResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZSOA_DATA_OPORTUNIDADAsync(ByVal ZSOA_DATA_OPORTUNIDAD1 As ZSOA_DATA_OPORTUNIDAD)
            Me.ZSOA_DATA_OPORTUNIDADAsync(ZSOA_DATA_OPORTUNIDAD1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZSOA_DATA_OPORTUNIDADAsync(ByVal ZSOA_DATA_OPORTUNIDAD1 As ZSOA_DATA_OPORTUNIDAD, ByVal userState As Object)
            If (Me.ZSOA_DATA_OPORTUNIDADOperationCompleted Is Nothing) Then
                Me.ZSOA_DATA_OPORTUNIDADOperationCompleted = AddressOf Me.OnZSOA_DATA_OPORTUNIDADOperationCompleted
            End If
            Me.InvokeAsync("ZSOA_DATA_OPORTUNIDAD", New Object() {ZSOA_DATA_OPORTUNIDAD1}, Me.ZSOA_DATA_OPORTUNIDADOperationCompleted, userState)
        End Sub
        
        Private Sub OnZSOA_DATA_OPORTUNIDADOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZSOA_DATA_OPORTUNIDADCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZSOA_DATA_OPORTUNIDADCompleted(Me, New ZSOA_DATA_OPORTUNIDADCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSOA_DATA_SOCIO_NEGOCIO
        
        Private iT_SOCIO_NEGOCIOField() As ZES_IP_SOCIO_NEGOCIO
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IT_SOCIO_NEGOCIO() As ZES_IP_SOCIO_NEGOCIO()
            Get
                Return Me.iT_SOCIO_NEGOCIOField
            End Get
            Set
                Me.iT_SOCIO_NEGOCIOField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_IP_SOCIO_NEGOCIO
        
        Private pARTNERField As String
        
        Private cORPORAField As String
        
        Private nORVISAField As String
        
        Private nAMEOR1Field As String
        
        Private mERCADOField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PARTNER() As String
            Get
                Return Me.pARTNERField
            End Get
            Set
                Me.pARTNERField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CORPORA() As String
            Get
                Return Me.cORPORAField
            End Get
            Set
                Me.cORPORAField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NORVISA() As String
            Get
                Return Me.nORVISAField
            End Get
            Set
                Me.nORVISAField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAMEOR1() As String
            Get
                Return Me.nAMEOR1Field
            End Get
            Set
                Me.nAMEOR1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MERCADO() As String
            Get
                Return Me.mERCADOField
            End Get
            Set
                Me.mERCADOField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_POSITION_OPORTUNIDAD
        
        Private nUMBER_INTField As String
        
        Private oRDERED_PRODField As String
        
        Private dESCRIPTIONField As String
        
        Private nET_VALUE_MANField As Decimal
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NUMBER_INT() As String
            Get
                Return Me.nUMBER_INTField
            End Get
            Set
                Me.nUMBER_INTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ORDERED_PROD() As String
            Get
                Return Me.oRDERED_PRODField
            End Get
            Set
                Me.oRDERED_PRODField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DESCRIPTION() As String
            Get
                Return Me.dESCRIPTIONField
            End Get
            Set
                Me.dESCRIPTIONField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NET_VALUE_MAN() As Decimal
            Get
                Return Me.nET_VALUE_MANField
            End Get
            Set
                Me.nET_VALUE_MANField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_BP_OPORTUNIDAD
        
        Private oBJECT_IDField As String
        
        Private dESCRIPTIONField As String
        
        Private pROCESS_TYPEField As String
        
        Private p_DESCRIPTION_20Field As String
        
      Private sTARTDATEField As String
        
      Private eXPECT_ENDField As String
        
        Private sTATField As String
        
        Private tXT30Field As String
        
        Private pARTNER_RESPField As String
        
        Private nAME_FIRST_RESPField As String
        
        Private nAME_LAST_RESPField As String
        
        Private pARTNER_INTField As String
        
        Private nAME_FIRST_INTField As String
        
        Private nAME_LAST_INTField As String
        
        Private cURRENCYField As String
        
        Private pOSITION_OField() As ZES_POSITION_OPORTUNIDAD
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OBJECT_ID() As String
            Get
                Return Me.oBJECT_IDField
            End Get
            Set
                Me.oBJECT_IDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DESCRIPTION() As String
            Get
                Return Me.dESCRIPTIONField
            End Get
            Set
                Me.dESCRIPTIONField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PROCESS_TYPE() As String
            Get
                Return Me.pROCESS_TYPEField
            End Get
            Set
                Me.pROCESS_TYPEField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property P_DESCRIPTION_20() As String
            Get
                Return Me.p_DESCRIPTION_20Field
            End Get
            Set
                Me.p_DESCRIPTION_20Field = value
            End Set
        End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property STARTDATE() As String
         Get
            Return Me.sTARTDATEField
         End Get
         Set(ByVal value As String)
            Me.sTARTDATEField = value
         End Set
      End Property
        
        '''<comentarios/>
      <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
      Public Property EXPECT_END() As String
         Get
            Return Me.eXPECT_ENDField
         End Get
         Set(ByVal value As String)
            Me.eXPECT_ENDField = value
         End Set
      End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property STAT() As String
            Get
                Return Me.sTATField
            End Get
            Set
                Me.sTATField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TXT30() As String
            Get
                Return Me.tXT30Field
            End Get
            Set
                Me.tXT30Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PARTNER_RESP() As String
            Get
                Return Me.pARTNER_RESPField
            End Get
            Set
                Me.pARTNER_RESPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAME_FIRST_RESP() As String
            Get
                Return Me.nAME_FIRST_RESPField
            End Get
            Set
                Me.nAME_FIRST_RESPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAME_LAST_RESP() As String
            Get
                Return Me.nAME_LAST_RESPField
            End Get
            Set
                Me.nAME_LAST_RESPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PARTNER_INT() As String
            Get
                Return Me.pARTNER_INTField
            End Get
            Set
                Me.pARTNER_INTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAME_FIRST_INT() As String
            Get
                Return Me.nAME_FIRST_INTField
            End Get
            Set
                Me.nAME_FIRST_INTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAME_LAST_INT() As String
            Get
                Return Me.nAME_LAST_INTField
            End Get
            Set
                Me.nAME_LAST_INTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CURRENCY() As String
            Get
                Return Me.cURRENCYField
            End Get
            Set
                Me.cURRENCYField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property POSITION_O() As ZES_POSITION_OPORTUNIDAD()
            Get
                Return Me.pOSITION_OField
            End Get
            Set
                Me.pOSITION_OField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_IP_OPORTUNIDAD
        
        Private oBJECT_IDField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OBJECT_ID() As String
            Get
                Return Me.oBJECT_IDField
            End Get
            Set
                Me.oBJECT_IDField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_BP_EMPLEADO
        
        Private pARTNERField As String
        
        Private nAME_FIRSTField As String
        
        Private nAME_LASTField As String
        
        Private pERNRField As String
        
        Private bU_SORT1Field As String
        
        Private fUNCIONField As String
        
        Private cARGOField As String
        
        Private oRG_VENTASField As String
        
        Private tORG_VENTASField As String
        
        Private oF_VENTASField As String
        
        Private tOF_VENTASField As String
        
        Private uNIDAD_ORGField As String
        
        Private tUNIDAD_ORGField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PARTNER() As String
            Get
                Return Me.pARTNERField
            End Get
            Set
                Me.pARTNERField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAME_FIRST() As String
            Get
                Return Me.nAME_FIRSTField
            End Get
            Set
                Me.nAME_FIRSTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAME_LAST() As String
            Get
                Return Me.nAME_LASTField
            End Get
            Set
                Me.nAME_LASTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PERNR() As String
            Get
                Return Me.pERNRField
            End Get
            Set
                Me.pERNRField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BU_SORT1() As String
            Get
                Return Me.bU_SORT1Field
            End Get
            Set
                Me.bU_SORT1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FUNCION() As String
            Get
                Return Me.fUNCIONField
            End Get
            Set
                Me.fUNCIONField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CARGO() As String
            Get
                Return Me.cARGOField
            End Get
            Set
                Me.cARGOField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ORG_VENTAS() As String
            Get
                Return Me.oRG_VENTASField
            End Get
            Set
                Me.oRG_VENTASField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TORG_VENTAS() As String
            Get
                Return Me.tORG_VENTASField
            End Get
            Set
                Me.tORG_VENTASField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OF_VENTAS() As String
            Get
                Return Me.oF_VENTASField
            End Get
            Set
                Me.oF_VENTASField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TOF_VENTAS() As String
            Get
                Return Me.tOF_VENTASField
            End Get
            Set
                Me.tOF_VENTASField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UNIDAD_ORG() As String
            Get
                Return Me.uNIDAD_ORGField
            End Get
            Set
                Me.uNIDAD_ORGField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TUNIDAD_ORG() As String
            Get
                Return Me.tUNIDAD_ORGField
            End Get
            Set
                Me.tUNIDAD_ORGField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_IP_EMPLEADO
        
        Private pARTNERField As String
        
        Private nAME_FIRSTField As String
        
        Private nAME_LASTField As String
        
        Private pERNRField As String
        
        Private bU_SORT1Field As String
        
        Private oRG_VENTASField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PARTNER() As String
            Get
                Return Me.pARTNERField
            End Get
            Set
                Me.pARTNERField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAME_FIRST() As String
            Get
                Return Me.nAME_FIRSTField
            End Get
            Set
                Me.nAME_FIRSTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAME_LAST() As String
            Get
                Return Me.nAME_LASTField
            End Get
            Set
                Me.nAME_LASTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PERNR() As String
            Get
                Return Me.pERNRField
            End Get
            Set
                Me.pERNRField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BU_SORT1() As String
            Get
                Return Me.bU_SORT1Field
            End Get
            Set
                Me.bU_SORT1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ORG_VENTAS() As String
            Get
                Return Me.oRG_VENTASField
            End Get
            Set
                Me.oRG_VENTASField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_PRODUCTS
        
        Private pRODUCT_IDField As String
        
        Private sHTEXT_1Field As String
        
        Private sHTEXT_2Field As String
        
        Private cATEGORY_IDField As String
        
        Private cATEGORY_TEXTField As String
        
        Private uNITField As String
        
        Private mSEHLField As String
        
        Private iTEM_CAT_GROUPField As String
        
        Private dESCRIPTION_20Field As String
        
        Private pRODUCT_TYPEField As String
        
        Private dESCRIPTIONField As String
        
        Private tEQUIPField As String
        
        Private tTEQUIPField As String
        
        Private tCOMBUSField As String
        
        Private tCOMBUSTField As String
        
        Private mARCAField As String
        
        Private mARCATField As String
        
        Private vALPRINField As String
        
        Private cLASIFField As String
        
        Private cLASIFTField As String
        
        Private mODELOPField As String
        
        Private dESPROVField As String
        
        Private vERSIONField As String
        
        Private mODEQUIVField As String
        
        Private gARANTField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PRODUCT_ID() As String
            Get
                Return Me.pRODUCT_IDField
            End Get
            Set
                Me.pRODUCT_IDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SHTEXT_1() As String
            Get
                Return Me.sHTEXT_1Field
            End Get
            Set
                Me.sHTEXT_1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SHTEXT_2() As String
            Get
                Return Me.sHTEXT_2Field
            End Get
            Set
                Me.sHTEXT_2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CATEGORY_ID() As String
            Get
                Return Me.cATEGORY_IDField
            End Get
            Set
                Me.cATEGORY_IDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CATEGORY_TEXT() As String
            Get
                Return Me.cATEGORY_TEXTField
            End Get
            Set
                Me.cATEGORY_TEXTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UNIT() As String
            Get
                Return Me.uNITField
            End Get
            Set
                Me.uNITField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MSEHL() As String
            Get
                Return Me.mSEHLField
            End Get
            Set
                Me.mSEHLField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM_CAT_GROUP() As String
            Get
                Return Me.iTEM_CAT_GROUPField
            End Get
            Set
                Me.iTEM_CAT_GROUPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DESCRIPTION_20() As String
            Get
                Return Me.dESCRIPTION_20Field
            End Get
            Set
                Me.dESCRIPTION_20Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PRODUCT_TYPE() As String
            Get
                Return Me.pRODUCT_TYPEField
            End Get
            Set
                Me.pRODUCT_TYPEField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DESCRIPTION() As String
            Get
                Return Me.dESCRIPTIONField
            End Get
            Set
                Me.dESCRIPTIONField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TEQUIP() As String
            Get
                Return Me.tEQUIPField
            End Get
            Set
                Me.tEQUIPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TTEQUIP() As String
            Get
                Return Me.tTEQUIPField
            End Get
            Set
                Me.tTEQUIPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TCOMBUS() As String
            Get
                Return Me.tCOMBUSField
            End Get
            Set
                Me.tCOMBUSField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TCOMBUST() As String
            Get
                Return Me.tCOMBUSTField
            End Get
            Set
                Me.tCOMBUSTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MARCA() As String
            Get
                Return Me.mARCAField
            End Get
            Set
                Me.mARCAField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MARCAT() As String
            Get
                Return Me.mARCATField
            End Get
            Set
                Me.mARCATField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALPRIN() As String
            Get
                Return Me.vALPRINField
            End Get
            Set
                Me.vALPRINField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASIF() As String
            Get
                Return Me.cLASIFField
            End Get
            Set
                Me.cLASIFField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASIFT() As String
            Get
                Return Me.cLASIFTField
            End Get
            Set
                Me.cLASIFTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MODELOP() As String
            Get
                Return Me.mODELOPField
            End Get
            Set
                Me.mODELOPField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DESPROV() As String
            Get
                Return Me.dESPROVField
            End Get
            Set
                Me.dESPROVField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VERSION() As String
            Get
                Return Me.vERSIONField
            End Get
            Set
                Me.vERSIONField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MODEQUIV() As String
            Get
                Return Me.mODEQUIVField
            End Get
            Set
                Me.mODEQUIVField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GARANT() As String
            Get
                Return Me.gARANTField
            End Get
            Set
                Me.gARANTField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_IP_PRODUCTOS
        
        Private pRODUCT_IDField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PRODUCT_ID() As String
            Get
                Return Me.pRODUCT_IDField
            End Get
            Set
                Me.pRODUCT_IDField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class BAPIRET2
        
        Private tYPEField As String
        
        Private idField As String
        
        Private nUMBERField As String
        
        Private mESSAGEField As String
        
        Private lOG_NOField As String
        
        Private lOG_MSG_NOField As String
        
        Private mESSAGE_V1Field As String
        
        Private mESSAGE_V2Field As String
        
        Private mESSAGE_V3Field As String
        
        Private mESSAGE_V4Field As String
        
        Private pARAMETERField As String
        
        Private rOWField As Integer
        
        Private fIELDField As String
        
        Private sYSTEMField As String
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property TYPE() As String
         Get
            Return Me.tYPEField
         End Get
         Set(ByVal value As String)
            Me.tYPEField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property ID() As String
         Get
            Return Me.idField
         End Get
         Set(ByVal value As String)
            Me.idField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property NUMBER() As String
         Get
            Return Me.nUMBERField
         End Get
         Set(ByVal value As String)
            Me.nUMBERField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE() As String
         Get
            Return Me.mESSAGEField
         End Get
         Set(ByVal value As String)
            Me.mESSAGEField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LOG_NO() As String
         Get
            Return Me.lOG_NOField
         End Get
         Set(ByVal value As String)
            Me.lOG_NOField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LOG_MSG_NO() As String
         Get
            Return Me.lOG_MSG_NOField
         End Get
         Set(ByVal value As String)
            Me.lOG_MSG_NOField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE_V1() As String
         Get
            Return Me.mESSAGE_V1Field
         End Get
         Set(ByVal value As String)
            Me.mESSAGE_V1Field = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE_V2() As String
         Get
            Return Me.mESSAGE_V2Field
         End Get
         Set(ByVal value As String)
            Me.mESSAGE_V2Field = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE_V3() As String
         Get
            Return Me.mESSAGE_V3Field
         End Get
         Set(ByVal value As String)
            Me.mESSAGE_V3Field = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MESSAGE_V4() As String
         Get
            Return Me.mESSAGE_V4Field
         End Get
         Set(ByVal value As String)
            Me.mESSAGE_V4Field = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property PARAMETER() As String
         Get
            Return Me.pARAMETERField
         End Get
         Set(ByVal value As String)
            Me.pARAMETERField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property ROW() As Integer
         Get
            Return Me.rOWField
         End Get
         Set(ByVal value As Integer)
            Me.rOWField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property FIELD() As String
         Get
            Return Me.fIELDField
         End Get
         Set(ByVal value As String)
            Me.fIELDField = Value
         End Set
      End Property
        
        '''<comentarios/>
      <SYSTEM.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property SYSTEM() As String
         Get
            Return Me.sYSTEMField
         End Get
         Set(ByVal value As String)
            Me.sYSTEMField = Value
         End Set
      End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZES_BP_SOCIO_NEGOCIO
        
        Private pARTNERField As String
        
        Private cORPORAField As String
        
        Private nORVISAField As String
        
        Private nAMEOR1Field As String
        
        Private mERCADOField As String
        
        Private mERCADODField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PARTNER() As String
            Get
                Return Me.pARTNERField
            End Get
            Set
                Me.pARTNERField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CORPORA() As String
            Get
                Return Me.cORPORAField
            End Get
            Set
                Me.cORPORAField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NORVISA() As String
            Get
                Return Me.nORVISAField
            End Get
            Set
                Me.nORVISAField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NAMEOR1() As String
            Get
                Return Me.nAMEOR1Field
            End Get
            Set
                Me.nAMEOR1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MERCADO() As String
            Get
                Return Me.mERCADOField
            End Get
            Set
                Me.mERCADOField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MERCADOD() As String
            Get
                Return Me.mERCADODField
            End Get
            Set
                Me.mERCADODField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSOA_DATA_SOCIO_NEGOCIOResponse
        
        Private eT_BP_SOCIO_NEGOCIOField() As ZES_BP_SOCIO_NEGOCIO
        
        Private eT_RETURNField() As BAPIRET2
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_BP_SOCIO_NEGOCIO() As ZES_BP_SOCIO_NEGOCIO()
            Get
                Return Me.eT_BP_SOCIO_NEGOCIOField
            End Get
            Set
                Me.eT_BP_SOCIO_NEGOCIOField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_RETURN() As BAPIRET2()
            Get
                Return Me.eT_RETURNField
            End Get
            Set
                Me.eT_RETURNField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSOA_DATA_PRODUCTS
        
        Private iT_PRODUCTOSField() As ZES_IP_PRODUCTOS
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IT_PRODUCTOS() As ZES_IP_PRODUCTOS()
            Get
                Return Me.iT_PRODUCTOSField
            End Get
            Set
                Me.iT_PRODUCTOSField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSOA_DATA_PRODUCTSResponse
        
        Private eT_PRODUCTSField() As ZES_PRODUCTS
        
        Private eT_RETURNField() As BAPIRET2
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_PRODUCTS() As ZES_PRODUCTS()
            Get
                Return Me.eT_PRODUCTSField
            End Get
            Set
                Me.eT_PRODUCTSField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_RETURN() As BAPIRET2()
            Get
                Return Me.eT_RETURNField
            End Get
            Set
                Me.eT_RETURNField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSOA_DATA_EMPLEADO
        
        Private iT_EMPLEADOField() As ZES_IP_EMPLEADO
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IT_EMPLEADO() As ZES_IP_EMPLEADO()
            Get
                Return Me.iT_EMPLEADOField
            End Get
            Set
                Me.iT_EMPLEADOField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSOA_DATA_EMPLEADOResponse
        
        Private eT_BP_EMPLEADOField() As ZES_BP_EMPLEADO
        
        Private eT_RETURNField() As BAPIRET2
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_BP_EMPLEADO() As ZES_BP_EMPLEADO()
            Get
                Return Me.eT_BP_EMPLEADOField
            End Get
            Set
                Me.eT_BP_EMPLEADOField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_RETURN() As BAPIRET2()
            Get
                Return Me.eT_RETURNField
            End Get
            Set
                Me.eT_RETURNField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSOA_DATA_OPORTUNIDAD
        
        Private iT_OBJECT_IDField() As ZES_IP_OPORTUNIDAD
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IT_OBJECT_ID() As ZES_IP_OPORTUNIDAD()
            Get
                Return Me.iT_OBJECT_IDField
            End Get
            Set
                Me.iT_OBJECT_IDField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSOA_DATA_OPORTUNIDADResponse
        
        Private eT_BP_OPORTUNIDADField() As ZES_BP_OPORTUNIDAD
        
        Private eT_RETURNField() As BAPIRET2
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_BP_OPORTUNIDAD() As ZES_BP_OPORTUNIDAD()
            Get
                Return Me.eT_BP_OPORTUNIDADField
            End Get
            Set
                Me.eT_BP_OPORTUNIDADField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_RETURN() As BAPIRET2()
            Get
                Return Me.eT_RETURNField
            End Get
            Set
                Me.eT_RETURNField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ZSOA_DATA_SOCIO_NEGOCIOCompletedEventHandler(ByVal sender As Object, ByVal e As ZSOA_DATA_SOCIO_NEGOCIOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZSOA_DATA_SOCIO_NEGOCIOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZSOA_DATA_SOCIO_NEGOCIOResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZSOA_DATA_SOCIO_NEGOCIOResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ZSOA_DATA_PRODUCTSCompletedEventHandler(ByVal sender As Object, ByVal e As ZSOA_DATA_PRODUCTSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZSOA_DATA_PRODUCTSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZSOA_DATA_PRODUCTSResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZSOA_DATA_PRODUCTSResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ZSOA_DATA_EMPLEADOCompletedEventHandler(ByVal sender As Object, ByVal e As ZSOA_DATA_EMPLEADOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZSOA_DATA_EMPLEADOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZSOA_DATA_EMPLEADOResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZSOA_DATA_EMPLEADOResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ZSOA_DATA_OPORTUNIDADCompletedEventHandler(ByVal sender As Object, ByVal e As ZSOA_DATA_OPORTUNIDADCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZSOA_DATA_OPORTUNIDADCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZSOA_DATA_OPORTUNIDADResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZSOA_DATA_OPORTUNIDADResponse)
            End Get
        End Property
    End Class
End Namespace
